### ISSUE TITLE
 How to fix "Stack offset of 4848 exceeded max offset please minimize large stack variables"

### ISSUE THREAD

**Issue by benhaben** [raydium-io/raydium-cpi-example#4]
anchor build
warning: virtual workspace defaulting to `resolver = "1"` despite one or more workspace members being on edition 2021 which implies `resolver = "2"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
note: for more details see https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions
Error: Function _ZN112_$LT$solana_program..instruction..InstructionError$u20$as$u20$solana_frozen_abi..abi_example..AbiEnumVisitor$GT$13visit_for_abi17hb774399f120246caE Stack offset of 4608 exceeded max offset of 4096 by 512 bytes, please minimize large stack variables
Error: Function _ZN108_$LT$solana_program..vote..state..CircBuf$LT$I$GT$$u20$as$u20$solana_frozen_abi..abi_example..AbiExample$GT$7example17h98dcdce08fbaab0aE Stack offset of 4640 exceeded max offset of 4096 by 544 bytes, please minimize large stack variables
Error: Function _ZN161_$LT$raydium_cp_swap..instructions..initialize..Initialize$u20$as$u20$anchor_lang..Accounts$LT$raydium_cp_swap..instructions..initialize..InitializeBumps$GT$$GT$12try_accounts17h2e95b717bced53b8E Stack offset of 4848 exceeded max offset of 4096 by 752 bytes, please minimize large stack variables
    Finished release [optimized] target(s) in 0.08s

**Comment by 0x777A** [comment]
If you set up the local development environment correctly according to the requirements in REAMDE, this problem will not occur.
