### ISSUE TITLE
 Program log: panicked at 'called `Option::unwrap()` on a `None` value', programs/amm/src/instructions/swap.rs:195:64

### ISSUE THREAD

**Issue by gladwinput** [raydium-io/raydium-cpi-example#5]
When you try to use the CLMM-CPI example you immediately encounter:
` Program log: panicked at 'called `Option::unwrap()` on a `None` value', programs/amm/src/instructions/swap.rs:195:64`

It appears that this is due to not passing in tick_arrays, Something to do with remaining_accounts.

It is unclear however where tick_arrays come from or how they go into the swap. The example remains incomplete and erroneous

**Comment by 0x777A** [comment]
I suggest you first understand the principles of CLMM. Our implementation is similar to Uniswap V3, and one concept is [Tick ](https://docs.uniswap.org/contracts/v3/reference/core/libraries/Tick), where ticks are stored in TickArray.

**Comment by KevinSheeranxyj** [comment]
@gladwinput have u solved this issue finally? I'm facing the same issue now
