### ISSUE TITLE
what are the values for devent variables configAddress, createPoolFeeReceive?

### ISSUE THREAD

**Issue by Nayyaroddeen** [raydium-io/raydium-cpi-example#6]
cpSwapProgram is docs but able to find other two.

getting the following error
Error during pool creation:  Error: Reached maximum depth for account resolution

**Comment by Nayyaroddeen** [comment]
@0x777A pls help

**Comment by 0x777A** [comment]
Fee reveiver: https://github.com/raydium-io/raydium-cp-swap/blob/master/programs/cp-swap/src/lib.rs#L38
configAddress: 9zSzfkYy6awexsHvmggeH36pfVUdDGyCcwmjT3AQPBj6
