### ISSUE TITLE
CP-Swap-CPI;  Error is->   "Access violation in stack frame 5 at address ..."

### ISSUE THREAD

**Issue by liupan163** [raydium-io/raydium-cpi-example#8]
hi, I try to call CP-Swap-CPI's method of  "cpi::accounts::Initialize",  
from this Demo "github.com/raydium-io/raydium-cpi-example/tree/master/cp-swap-cpi" and "proxy_initialize(...)"

but it responds with the Error "program  failed: Access violation in stack frame 5 at address 0x200005ff8 of size 8 at BPF instruction #10536".

After checking the related solution,  I've added  'Box<>'  for nearly all params,  But it still does not work.
Could Anyone help to solve it? Thanks a lot.

**Comment by porkytheblack** [comment]
how did you fix this?
I see you marked it as completed

**Comment by liupan163** [comment]
> how did you fix this? I see you marked it as completed

yes, the root reason is something is wrong with my local env, the above error hint is a little misleading.

**Comment by porkytheblack** [comment]
in my case it happens when I try on devnet
